fix two changes at one second in the cronfile
vixie/cron pull request #2
Opened 2021-08-12 09:34 UTC by soroosh-sdi

Bug Explanation:
1- A cron-file exists in /var/cron/tabs/root
2-Assume in the first milliseconds of  01:01:00,  someone changed the cron file into this:
* * * * *   root  /bin/true
3-Just after storing that cron-file, cron binary wakes up and scans SPOOL_DIR; it finds out there is a change in /var/cron/tabs/root file, so update its database and store the 'last modified timestamp' of the SPOOL_DIR into new_db.mtime.
4- So far so good, but the second 01:01:00 still is not ended. Meanwhile,  the user changes the /var/cron/tabs/root file again to the following:
* * * * *   root  /bin/true
5- After 60 seconds cron binary wakes up again and sees the database.mtime is equal to SPOOL_DIR.mtime.

Solution:
1- Reload the database even when mtime is equal to SPOOL_DIR.mtime.
2- Store time(NULL) to the database.mtime.

Signed-off-by: soroosh-sdi <soroosh.sardari@gmail.com>

2021-08-14 05:52 UTC, vixie requested changes
thank you for your bug report. i agree that there is a bug here, triggered when a crontab is modified twice in the same wall second. i think time(NULL) is the wrong replacement value, since load_database() may run during the same wall second that the first and second crontab modification both occurred within. a more reliable fix, though not without problems, would be to use the timespec rather than the time. (when cron was written, statbuf had only st_mtime, and not yet st_mtim.{tv.sec,tv_nsec} as it does today. this would not be a complete fix, since the file could be revised more than once per nanosecond. however, we must not go as far as to checksum the file, or else cron would use far too many system resources. do you wish to amend your patch to make it compare and store timespecs, and avoid time(NULL)? if not i will make that change and ask you to test it. thanks again for your interest in cron.

2021-08-14 19:22 UTC, soroosh-sdi commented
@vixie 
I don't agree, I'm afraid. Using time(NULL) is correct but it is not the ideal solution. As you mentioned time(NULL) is equal to SPOOL_DIR.mtime, so cron reload the database once again in the next round and this time time(NULL) is greater than SPOOL_DIR.mtime.
However, using st_mtim.{tv.sec,tv_nsec} can prevent the second reload but it could have the same bug very rarely.
I don't have any preference between these two, only wanted to clarify my solution. Please let me know which one is your choice then I will implement it.

2021-08-14 21:46 UTC, vixie commented
the incidence of time(NULL) producing resource waste is high, whereas the incidence of timespec comparisons doing so is low.

therefore, i hope you will consider reverting your proposed change, and implementing timespec comparisons instead.

2021-08-15 06:40 UTC, soroosh-sdi commented
@vixie 
please, review again.

2021-08-15 07:24 UTC, vixie commented
is_greater_than(a,b)==TRUE has an extraneous "==TRUE".
is_greater_than(a,b) is adequate, and clearer.
(database.c:28).

TEQUAL should use spaces around ==, consistently. (database.c:29)

is_greater_than()'s return type should be bool, not u_int_8.
(database.c:31)

use spacing in your added code which is consistent with the rest
of the source file. (database.c:31, :32, :34)

unless you intend that {s,n} be greater than {s-1,any} but that
{s,n} not be greater than {s,n-1}, i think you have reversed the
sense of the comparison in database.c:36 (see also database.c:32).

"else return" has an extraneous "else".
"return" is adequate, and clearer.
(database.c:36)

initializing tv_sec without also initializing tv_nsec leaves
tv_nsec undefined. use a structure {0,0} to initialize the full
mtim structure. (database.c:65)

do not put a space before a comma. (database.c:74)

compare the timespec not just tv_sec, perhaps using TEQUAL.
(database.c:88) (note, the original code incorrectly treats
a time_t as if it were a boolean, and should have been written
as "if (syscron_stat.st_time != 0)". i should not have published
it that way.

do not put a space after a left-parenthesis. (database.c:235)

please indicate the testing status of this change -- is there a
regression test which now reliably succeeds after the change but
which reliably failed before the change?

2021-08-15 08:07 UTC, soroosh-sdi commented
I'm going to fix this issues tonight.
I had a complicated scenario that occasionally failed. After lots of debugging, finally  I found this issue. but for this contribution I only tested it in an lxc-container and not in automated way!
I can write a simple python script to reproduce this bug, if you want.

2021-08-15 16:56 UTC, vixie commented
there's no regression suite contained within cron, so a python script
would be welcome but unexpected. a comment in this thread showing the
failure and non-failure, would be enough.

2021-08-15 19:52 UTC, soroosh-sdi commented
@vixie 
Please review
Test Status : NOT COMPLETE

2021-08-15 23:55 UTC, vixie commented
this looks pretty good -- thanks. i wonder if we should make "static const struct timespec ts_zero;" and use that everywhere you have {tv_sec = 0, tv_nsec = 0}, mostly for clarity but perhaps also for performance on obscure platforms. let me know what you think, and also, about testing. thanks again.

2021-08-16 06:00 UTC, soroosh-sdi commented
using `ts_zero` is a good idea. I added in my last commit.
Test Status: PASS

2021-08-16 15:49 UTC, vixie requested changes
i think there's a need for ts_zero to not be static and therefore not defined in database.c. cron.c:129 is my reason. what's your opinion?

2021-08-17 12:10 UTC, soroosh-sdi commented
I think we have two options:
1 - define ts_zero as a macro in some .h file maybe cron.h
2 - define an extern global variable
I prefer the global variable, I will push my code.

2021-08-17 15:03 UTC, vixie commented
On Tue, Aug 17, 2021 at 05:11:01AM -0700, Soroosh Sardari wrote:
> I think we have two options:
> 1 - define ts_zero as a macro in some .h file maybe cron.h
> 2 - define an extern global variable
> I prefer the global variable, I will push my code.

let's go with #2.

-- 
Paul Vixie

2021-08-18 08:03 UTC, soroosh-sdi commented
pushed the last changes, if its OK let me know to squash all the commits.

2021-08-18 16:06 UTC, vixie requested changes
please move the definition of ts_zero to globals.h, and remove the extern reference. use the XTRN and INIT macros as is done for the other global variables declared there.

2021-08-18 19:34 UTC, soroosh-sdi commented
INIT doesn't work for initializing ts_zero, compiler thinks I'm passing  two args into INIT. I used the other way that used in that file.

2021-08-19 18:27 UTC, vixie approved these changes
i made two changes, very minor. it looks good to me!

2021-08-19 18:28 UTC, merged

2021-08-19 18:48 UTC, soroosh-sdi commented
Thanks